site_name: Sandrun Documentation
site_description: Anonymous, ephemeral, sandboxed code execution service
site_author: Sandrun Team
site_url: https://yourusername.github.io/sandrun/

repo_name: sandrun
repo_url: https://github.com/yourusername/sandrun
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Job Manifest: job-manifest.md
  - Architecture: architecture.md

  - Integrations:
    - Trusted Pool: integrations/trusted-pool.md
    - Broker: integrations/broker.md
    - MCP Server: integrations/mcp-server.md

  - Development:
    - Building: development/building.md
    - Testing: development/testing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/sandrun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

copyright: Copyright &copy; 2025 Sandrun Team
